version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Use an appropriate base image for your project

    steps:
      - checkout

      # Run the build for each component based on the matrix
      - run:
          name: Build component ${{ matrix.component }}
          command: |
            cd apps/${{ matrix.component }}
            circleci config process .circleci/config.yml > .circleci/processed-config.yml
            circleci local execute -c .circleci/processed-config.yml

workflows:
  version: 2
  build:
    jobs:
      - build:
          matrix:
            components:
              - sample-back
              - sample-front
