# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
    - image: cimg/base:2023.06
    steps:
    - checkout
    - run: "echo build"
  deploy:
    docker:
    - image: cimg/base:2023.06
    steps:
    - checkout
    - run: "echo deploy"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_and_test:
    jobs:
    - build
    - deploy:
        type: approval
        requires:
        - build
