version: 2.1

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Execute matrix job
          command: |
            circleci local execute -c apps/$MATRIX_VALUE/.circleci/config.yml --job build
workflows:
  version: 2
  build:
    jobs:
      - build:
          matrix:
            name: MATRIX_VALUE
            values:
              - sample-back
              - sample-front

executors:
  docker-executor:
    docker:
      - image: your-docker-image # Replace with your desired Docker image
