name: Deployment

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ["coop-back", "coop-front"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      packages: write
    steps:
      - name: test
        run: echo "Ting tong"
