name: Deployment

on:
  push:

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, rct, sta]
        app: [coop-front, coop-back]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Deploy
        run: echo "Ting tong"
