name: Deployment

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        app: ["coop-back", "coop-front"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      packages: write
    steps:
      - name: test
        run: echo "Ting tong"
  deployment:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, rct, sta]
        app: [coop-front, coop-back]
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Deploy
        run: echo "Ting tong"
